spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/restaurant/**

