spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/restaurant/**

        - id: food-service
          uri: http://localhost:8084
          predicates:
            - Path=/food/**

        - id: cart-service
          uri: http://localhost:8085
          predicates:
            - Path=/shoppingCart/**

